### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by ttt789-ppo** [bitsavers/eu_ex#2]
<img width="682" alt="屏幕截图 2022-03-17 154046" src="https://user-images.githubusercontent.com/72877282/158760378-5aa3a3e0-1d70-4516-8dc5-e4e6514abda1.png">

**Comment by ZetaoYang** [comment]
仔细阅读 https://github.com/bitsavers/eu_ex#constant-variable-setting，根据你的截图 `LOGIN_PIN_SENDER` 和 `RENEW_PIN_SENDER` 都应设置为 `Mailparser`, 默认是 `ZapierAirtable`. https://github.com/bitsavers/eu_ex/blob/main/main.py#L52 
https://github.com/bitsavers/eu_ex/blob/main/main.py#L54

**Comment by ttt789-ppo** [comment]
> 仔细阅读 https://github.com/bitsavers/eu_ex#constant-variable-setting ，根据你的截图 `LOGIN_PIN_SENDER` 和 `RENEW_PIN_SENDER` 都应设置为 `Mailparser`, 默认是 `ZapierAirtable`. https://github.com/bitsavers/eu_ex/blob/main/main.py#L52 https://github.com/bitsavers/eu_ex/blob/main/main.py#L54

可是我设置了呀，图上有LOGIN_PIN_SENDER 和 RENEW_PIN_SENDER，是mailparser,在screct里设置的

**Comment by ZetaoYang** [comment]
`LOGIN_PIN_SENDER` 和 `RENEW_PIN_SENDER` 是常量，直接在 main.py 里改，没有从环境变量里获取。

**Comment by ttt789-ppo** [comment]
> `LOGIN_PIN_SENDER` 和 `RENEW_PIN_SENDER` 是常量，直接在 main.py 里改，没有从环境变量里获取。

哦哦，谢谢大佬，大佬我这个action的yml是复制其他项目改的，当时不行以后我就删除了，找不到了，请问您有action的程序吗

**Comment by ZetaoYang** [comment]
```yaml
name: 'EUserv Auto Extend'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Setup Python3'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: 'Install dependencies'
        run: |
          python3 -m pip install -r requirements.txt
      - name: 'Auto_renew'
        env:
          CUSTOMERIDS: ${{ secrets.CUSTOMERIDS }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
          # using my own apikey
          TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}
          TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}
          MAILPARSER_DL_IDS_FOR_LOGIN: ${{ secrets.MAILPARSER_DL_IDS_FOR_LOGIN }}
          MAILPARSER_DL_IDS_FOR_RENEW: ${{ secrets.MAILPARSER_DL_IDS_FOR_RENEW }}
        run: python3 main.py
```
只是个例子，适用于 LOGIN_PIN_SENDER 和 RENEW_PIN_SENDER 都为 `Mailparser` 的情况，crontab 定时注释掉了。
